# Métodos de ensamblados

A pesar de la omnipresencia de los modelos de IA que parecieran ser la mejor herramienta de modelamiento que existe, hay que mencionar que a lo que se refiere a datos tabulares “el estado del arte” siguen siendo los modelos de ensamblados.  En este jupyter notebook haremos una breve  taxonomía de estos métodos y un ejemplo práctico de cada familia.


Sin entrar en definiciones rigurosas , los métodos de ensamblado corresponden a lo que en jerga popular se llama “la opinión de los expertos”. Corresponde a una técnica donde se utilizan varios modelos a la vez. La idea central es generar “diversidad”.Esto en términos generales se logra  ajustando distintos modelos en distintas porciones de los datos. A la hora de predecir se combina la predicción de cada modelo individual.

# Ensamblados paralelos homogéneos

Corresponden al tipo de ensamblado donde todos los modelos base son del mismo tipo. Como por ejemplo árboles de decisión. Paralelo se refiere a que todos los modelos se entrenan  en forma independiente. Dentro de este grupo podemos encontrar al random forest, bagging , pasting, etc.  En el ejemplo de a continuación implementaremos un random forest.


Los datos utilizados para este ejemplo provienen de kaggle , corresponde a un conjunto sintético , que simula ciertas variables fisiológicas,morfológicas y su impacto en el riesgo de padecer diabetes. Utilizaremos esta última variable como respuesta y crearemos un modelo que nos diga cuales son las variables asociadas a un mayor riesgo.  Una de las ventajas de random forest es que no requiere procesamiento de los atributos.

In [13]:
import kagglehub
import pandas as pd
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelBinarizer 
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [ ]:
path = kagglehub.dataset_download("vishardmehta/diabetes-risk-prediction-dataset", output_dir="./data")

In [3]:
df = pd.read_csv("data/diabetes_risk_dataset.csv")
df.head()

   Patient_ID  age  ... diabetes_risk_score  diabetes_risk_category
0           1   77  ...                52.3             Prediabetes
1           2   54  ...                 3.7                Low Risk
2           3   25  ...                87.3               High Risk
3           4   23  ...                76.1               High Risk
4           5   70  ...                47.7             Prediabetes

[5 rows x 19 columns]

In [10]:
df_encode = pd.get_dummies(df, columns=['gender','physical_activity_level','family_history_diabetes','diabetes_risk_category'],dtype=int)

In [11]:
df_encode.head()

   Patient_ID  ...  diabetes_risk_category_Prediabetes
0           1  ...                                   1
1           2  ...                                   0
2           3  ...                                   0
3           4  ...                                   0
4           5  ...                                   1

[5 rows x 25 columns]

In [16]:
X = df.drop(['diabetes_risk_category', 'Patient_ID'], axis=1)
Y = df['Patient_ID']